= Setting Up A Gradle Project
Jordan Bergin
:jbake-created: 27 March 2022
:jbake-type: post
:jbake-status: published
:jbake-tags: gradle, kotlin, kts
:idprefix:

The intention of this blog post is provide steps that take the user from an empty directory, to a working Gradle project. Making the project do something useful is out of scope.

== Prerequisites

This blog post assumes you have Java and Gradle installed on your machine.

== Set Up

To begin with, create an empty directory with the name of your project. This isn't a strict requirement as Gradle does allow you to specify the project's name as we will see later on, but it is a sane choice of naming for project folders.

If you are using Intellij IDEA (recommended) then the default location for your projects would be under your `~/IdeaProjects` directory.

== Add Gradle Files

Create two files in your empty directory, one called `build.gradle.kts` and another called `settings.gradle.kts`.

== Create The Wrapper

Gradle wrappers are not actually the Gradle tool themselves, but a tool provided by Gradle, to download a specific version of Gradle specific to this project. The wrapper consists of:

* `gradlew` and `gradlew.bat` scripts that can run on *nix or Windows machines
* A `gradle-wrapper.jar` which is called by said scripts to download Gradle
* A `gradle-wrapper.properties` file which controls the behaviour of the above script and jar (for example, you can find the URL which is used to download the Gradle version specified by this wrapper)

The wrapper ensures that for this project you always use the same version of Gradle (since you might have multiple projects each with different Gradle requirements!).

Now, in your directory run the following from your terminal:

`gradle wrapper --gradle-version=<YOUR CHOICE OF VERSION HERE>`

This will initialise the Gradle Wrapper for your project using the specified version. It is advised (unless you have requirements to use older versions) to use the latest Gradle Version published by Gradle.

Note: Now you have defined the wrapper for your project, you no longer need to call the `gradle` command, but simply run the `./gradlew` script instead, for example if you wanted to upgrade to gradle 7.4.1 you can now do this in your project:

`./gradle wrapper --gradle-version=7.4.1`

== Summary

That's it, you have created a Gradle project. It may not do anything useful yet, but this is all you need to get started with Gradle. For example, you should now be able to run `./gradlew javaToolchains` to have your Gradle project print out what versions of Java it has found on your local machine that it can use.

